### ISSUE TITLE
Backend CCRP - Authentication

### ISSUE THREAD

**Issue by Khyati729** [Carbonable/carbonable-ccrp-backend#33]
As carbonable 
I want to add an auth module
In order to secure api access

[nodeJS/TypeScript]

### Rules

1. Use this [documentation](https://docs.nestjs.com/security/authentication) to create the authentication management with JWT
2. Users can have the role admin or user - [Documentation](https://docs.nestjs.com/security/authorization)
3. Make all the existing api public
4. Create the "create user" (login, password, default role is user) api which is only accessible for an admin
5. Create the swagger doc in the controller

**Comment by fishonamos** [comment]
I will love to work on this.

**Comment by LouGel** [comment]
Id love to improve my skills on NestJs on this.

**Comment by schwepps** [comment]
Hi @fishonamos and @LouGel! Thanks for your interest in Carbonable and this issue.
I'm really sorry @fishonamos, @LouGel is going to work on this issue.
We had started the discussion outside github before you asked. It's a bit off process and we will do better next time.
I hope you'll find on other issue to work on. 
Unfortunately we don't have a lot of nodeJS issue this time but we will have more for the next OD Hack.

**Comment by fishonamos** [comment]
Thats fair  @schwepps, since you have started a conversation on the issue with @LouGel. I commented on this issue to [Upgrade the all repository from Cairo 2.2.0 to 2.6.0 with it's dependencies](https://github.com/Carbonable/carbon-protocol/issues/338)
